

DROP TABLE CLIENTES PURGE;
CREATE TABLE CLIENTES (
  id    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  nome  VARCHAR2(100) NOT NULL,
  email VARCHAR2(120) UNIQUE
);

INSERT INTO CLIENTES (nome, email) VALUES ('Vinicius Vieira', 'vinizinho157@gmail.com');
INSERT INTO CLIENTES (nome, email) VALUES ('Pedrinho', 'Pedro157@gmail.com');
INSERT INTO CLIENTES (nome, email) VALUES ('Nicolas', 'Nicolas157@gmail.com');

SELECT nome, email FROM CLIENTES 


CREATE TABLE PRODUTOS (
  id     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  nome   VARCHAR2(100) NOT NULL,
  preco  NUMBER(10,2)  NOT NULL CHECK (preco >= 0),
  tipo   VARCHAR2(50) NOT NULL
);

INSERT INTO PRODUTOS (nome, preco, tipo) VALUES ('Notebook X', 3000, 'Notebook');
INSERT INTO PRODUTOS (nome, preco, tipo) VALUES ('Notebook Y', 3500, 'Notebook');
INSERT INTO PRODUTOS (nome, preco, tipo) VALUES ('Celular Z', 2000, 'Celular');

UPDATE PRODUTOS SET preco = 3300 WHERE id = '2';
UPDATE PRODUTOS SET preco = 3850 WHERE id = '3';

SELECT id,nome, preco, tipo FROM PRODUTOS 

CREATE TABLE PEDIDOS (
  id         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  cliente_id NUMBER NOT NULL,
  produto_id NUMBER NOT NULL,
  status     VARCHAR2(20) NOT NULL CHECK (status IN ('ABERTO','FINALIZADO','CANCELADO'))
);

INSERT INTO PEDIDOS (cliente_id, produto_id, status) VALUES (1, 1, 'ABERTO')
INSERT INTO PEDIDOS (cliente_id, produto_id, status) VALUES (2, 2, 'CANCELADO')
INSERT  INTO PEDIDOS (cliente_id, produto_id, status) VALUES (3, 3, 'FINALIZADO')
INSERT  INTO PEDIDOS (cliente_id, produto_id, status) VALUES (1, 2, 'CANCELADO')

SELECT CLIENTE_ID, PRODUTO_ID, STATUS FROM PEDIDOS

DELETE FROM PEDIDOS WHERE status = 'CANCELADO';


CREATE TABLE CLIENTES_STG (
  nome  VARCHAR2(100) NOT NULL,
  email VARCHAR2(120) NOT NULL
);

INSERT INTO CLIENTES_STG (nome, email) VALUES ('Ana P. Atualizada', 'ana@techplus.com')
INSERT INTO CLIENTES_STG (nome, email) VALUES ('Daniela Nova', 'daniela@techplus.com')

MERGE INTO CLIENTES c
USING CLIENTES_STG n
ON (c.email = n.email)
WHEN MATCHED THEN
    UPDATE SET c.nome = n.nome
WHEN NOT MATCHED THEN
    INSERT (nome, email) VALUES (n.nome, n.email);
    SELECT nome, email STATUS FROM CLIENTES


